# This is a basic workflow to help you get started with Actions

name: Build and publish documentation on GH pages

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the dev branch
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
         
      - name: Build docs
        run: |
          cd ./docs
          sphinx-apidoc -f -o --separate . ../src
          make html

      - name: Publish docs
        run: |
          GH_BASE_BRANCH=$(git branch | cut -f 2 -d" ")
          rm -rf /tmp/gh-pages
          cp -r docs/_build/html /tmp/gh-pages
          git checkout gh-pages
          rm -rf *
          cp -a /tmp/gh-pages/. .
          git commit -am "Updated the documentation"
          git push origin gh-pages