name: Build and publish documentation on GH pages

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
         
      - name: Sphinx Build
        uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: docs/
          build-command: make html
          pre-build-command: "pip install -U pip && pip install sphinx && sphinx-apidoc --separate -f -o docs/ src/"

      - name: Publish Artifact
        uses: actions/upload-artifact@v2.2.0
        with:
          name: documentation
          path: docs/_build/html
          retention-days: 5
          if-no-files-found: error
          
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
          
      - name: Empty the repo
        run: |
          rm -rf *
          
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: documentation
          
      - name: Commit changes
        run: |
          git config --local user.email "workflows@github.com"
          git config --local user.name "GitHub Workflows"
          git commit -am "Update documentation" -a || true
      
      - name: Push changes
        uses: actions/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
